import { createContext, useContext, useEffect, useState, type ReactNode } from "react";

export type Lang = "th" | "en" | "zh";

export const LANG_OPTIONS: { code: Lang; label: string; native: string; flag: string }[] = [
  { code: "th", label: "Thai",    native: "ไทย",     flag: "🇹🇭" },
  { code: "en", label: "English", native: "English", flag: "🇬🇧" },
  { code: "zh", label: "Chinese", native: "中文",     flag: "🇨🇳" },
];

const translations = {
  th: {
    /* ===== appbar / common ===== */
    menu_home:          "หน้าหลัก",
    menu_products:      "ผลิตภัณท์",
    menu_market:        "Herbal Market",
    menu_blog:          "สาระความรู้",
    menu_about:         "เกี่ยวกับเรา",
    button_login:       "เข้าสู่ระบบ",
    search_placeholder: "ค้นหาสินค้า สมุนไพร แบรนด์...",
    search_button:      "ค้นหา",
    search_aria:        "ค้นหา",
    close_aria:         "ปิด",

    /* ===== common ===== */
    common_back:           "กลับ",
    common_cancel:         "ยกเลิก",
    common_save:           "บันทึก",
    common_confirm:        "ยืนยัน",
    common_edit:           "แก้ไข",
    common_delete:         "ลบ",
    common_change:         "เปลี่ยน",
    common_loading:        "กำลังโหลด...",
    common_or:             "หรือ",
    common_view_all:       "ดูทั้งหมด",
    common_view_details:   "ดูรายละเอียด",
    common_read_more:      "อ่านเพิ่มเติม",
    common_required:       "กรุณากรอกข้อมูลให้ครบ",
    common_yes:            "ใช่",
    common_no:             "ไม่",
    common_close:          "ปิด",
    common_submit:         "ส่ง",
    common_send:           "ส่งข้อความ",
    common_continue:       "ดำเนินการต่อ",
    common_shop_now:       "ไปช้อปปิ้ง",
    common_continue_shop:  "ช้อปปิ้งต่อ",
    common_apply:          "ใช้",
    common_items:          "รายการ",
    common_pieces:         "ชิ้น",
    common_pcs:            "ชิ้น",
    common_qty:            "จำนวน",
    common_total:          "รวม",
    common_subtotal:       "ยอดรวม",
    common_discount:       "ส่วนลด",
    common_shipping:       "ค่าจัดส่ง",
    common_free:           "ฟรี",
    common_sort:           "เรียงตาม",
    common_sort_desc:      "จากมากไปน้อย",
    common_sort_asc:       "จากน้อยไปมาก",
    common_filter:         "ตัวกรอง",
    common_reset_filter:   "ล้างตัวกรอง",
    common_prev_page:      "หน้าก่อน",
    common_next_page:      "หน้าถัดไป",
    common_no_orders:      "ไม่มีคำสั่งซื้อ",
    common_not_found:      "ไม่พบข้อมูล",
    common_optional:       "ไม่บังคับ",
    common_required_mark:  "*",
    common_search_results: "ผลการค้นหา",
    common_results_found:  "พบ",

    /* ===== login / register ===== */
    login_welcome:         "ยินดีต้อนรับเข้าสู่ระบบ",
    login_subtitle:        "ดูแลสุขภาพอย่างมั่นใจ ด้วยผลิตภัณฑ์สมุนไพรคัดสรร",
    login_subtitle2:       "ช้อปออนไลน์ได้แล้วที่ Metaherb",
    login_email_label:     "อีเมลหรือชื่อผู้ใช้",
    login_email_ph:        "กรอกอีเมลหรือชื่อผู้ใช้",
    login_password_label:  "รหัสผ่าน",
    login_password_ph:     "กรอกรหัสผ่าน",
    login_forgot:          "ลืมรหัสผ่าน?",
    login_demo:            "บัญชีทดสอบ (กดเพื่อกรอกอัตโนมัติ):",
    login_button:          "เข้าสู่ระบบ",
    login_no_account:      "คุณยังไม่มีบัญชีผู้ใช้",
    login_register_link:   "ลงทะเบียน",
    login_invalid:         "อีเมลหรือรหัสผ่านไม่ถูกต้อง",
    register_title:        "สมัครสมาชิก",
    register_role_label:   "ประเภทบัญชี",
    register_role_user:    "ผู้ซื้อ",
    register_role_owner:   "ร้านค้า",
    register_username_label:"ชื่อผู้ใช้",
    register_username_ph:  "ระบุชื่อผู้ใช้",
    register_password_label:"รหัสผ่าน",
    register_password_ph:  "ระบุรหัสผ่านอย่างน้อย 8 ตัว",
    register_email_label:  "อีเมล",
    register_email_ph:     "ระบุอีเมล",
    register_phone_label:  "เบอร์โทรศัพท์",
    register_phone_ph:     "ระบุเบอร์โทรศัพท์",
    register_accept:       "ยอมรับ",
    register_terms:        "ข้อกำหนดการใช้บริการ meta herb",
    register_and:          "และ",
    register_privacy:      "นโยบายความคุ้มครองข้อมูลส่วนบุคคล",
    register_button:       "สมัครสมาชิก",
    register_has_account:  "คุณมีบัญชีอยู่แล้ว?",
    register_login_link:   "เข้าสู่ระบบ",
    register_password_min: "รหัสผ่านต้องมีอย่างน้อย 8 ตัวอักษร",
    register_accept_terms: "กรุณายอมรับข้อกำหนด",

    /* ===== home ===== */
    home_recommended:      "สินค้าแนะนำ",
    home_flash_sale:       "Flash Sale",
    home_articles:         "บทความแนะนำ",
    home_videos:           "วีดีโอแนะนำ",
    home_recommended_tag:  "สินค้าแนะนำ",
    home_discount_prefix:  "ลด",
    cat_herb:              "สมุนไพร",
    cat_food:              "อาหาร",
    cat_medicine:          "ยา",
    cat_aroma:             "เครื่องหอม",
    cat_beauty:            "ความสวย",
    cat_giftset:           "ชุดของขวัญ",
    cat_tea:               "ชาสมุนไพร",
    cat_supplement:        "อาหารเสริม",
    cat_oil:               "น้ำมันสกัด",

    /* ===== products ===== */
    products_title:        "ผลิตภัณฑ์ทั้งหมด",
    products_filter:       "ตัวกรอง",
    products_category:     "หมวดหมู่",
    products_type:         "ประเภทสินค้า",
    products_price_range:  "ช่วงราคา",
    products_all:          "ทั้งหมด",
    products_type_flash:   "สินค้า Flash Sale",
    products_type_promo:   "สินค้าโปรโมชัน",
    products_type_rec:     "สินค้าแนะนำ",
    products_showing:      "แสดง",
    products_of:           "จาก",
    products_results:      "รายการ",

    /* ===== product detail ===== */
    pd_back_to_products:   "กลับสู่หน้าสินค้า",
    pd_in_stock:           "มีสินค้า",
    pd_out_of_stock:       "สินค้าหมด",
    pd_quantity:           "จำนวน",
    pd_available:          "มีสินค้า",
    pd_options:            "ตัวเลือก",
    pd_select_option:      "เลือกตัวเลือก",
    pd_add_to_cart:        "เพิ่มลงรถเข็น",
    pd_buy_now:            "ซื้อเลย",
    pd_chat:               "แชทกับร้านค้า",
    pd_description:        "รายละเอียดสินค้า",
    pd_specs:              "ข้อมูลจำเพาะ",
    pd_reviews:            "รีวิวสินค้า",
    pd_related:            "สินค้าที่เกี่ยวข้อง",
    pd_sold:               "ขายแล้ว",
    pd_rating:             "คะแนน",
    pd_shop:               "ร้านค้า",
    pd_visit_shop:         "เยี่ยมชมร้าน",
    pd_added_to_cart:      "เพิ่มลงรถเข็นแล้ว",
    pd_added_to_wishlist:  "เพิ่มในสินค้าที่ชอบแล้ว",
    pd_removed_from_wishlist:"ลบออกจากสินค้าที่ชอบแล้ว",
    pd_select_option_first:"กรุณาเลือกตัวเลือก",
    pd_share:              "แชร์",
    pd_copy_link:          "คัดลอกลิงก์แล้ว!",
    pd_all_reviews:        "รีวิวทั้งหมด",
    pd_write_review:       "เขียนรีวิว",
    pd_filter_reviews:     "กรองรีวิว",
    pd_with_image:         "พร้อมรูปภาพ",
    pd_specifications:     "ข้อมูลจำเพาะ",
    pd_no_reviews:         "ยังไม่มีรีวิว",
    pd_price:              "ราคาสินค้า",
    pd_options_label:      "ตัวเลือกสินค้า",
    pd_quantity_label:     "จำนวนสินค้า",
    pd_remaining:          "เหลือเพียง",
    pd_add_to_cart_btn:    "เพิ่มไปยังรถเข็น",
    pd_added_btn:          "เพิ่มแล้ว!",
    pd_buy_now_btn:        "ซื้อสินค้า",
    pd_product_details:    "รายละเอียดผลิตภัณฑ์",
    pd_product_specs:      "ข้อมูลจำเพาะ",
    pd_weight:             "น้ำหนักสุทธิ:",
    pd_type:               "ประเภท:",
    pd_sku:                "รหัสสินค้า:",
    pd_format:             "รูปแบบ:",
    pd_shop_items:         "รายการสินค้า",
    pd_shop_items_unit:    "รายการ",
    pd_shop_rating:        "คะแนนร้านค้า",
    pd_all_ratings:        "การให้คะแนนทั้งหมด 100",
    pd_loved_items:        "ถูกใจสินค้า",
    pd_view_shop:          "ดูร้านค้า",
    pd_ask_shop:           "ถามร้านค้า",
    pd_review_option_prefix:"ตัวเลือกสินค้า:",
    pd_recommended_for_you:"สินค้าเหมาะกับคุณ",
    pd_all_filter:         "ทั้งหมด",
    pd_view_review_image:  "ดูรูปรีวิว",
    pd_prev:               "ก่อนหน้า",
    pd_next:               "ถัดไป",

    /* ===== cart ===== */
    cart_title:            "รถเข็น",
    cart_empty:            "รถเข็นว่างเปล่า",
    cart_empty_sub:        "เพิ่มสินค้าที่คุณชื่นชอบลงในรถเข็น",
    cart_select_all:       "เลือกทั้งหมด",
    cart_delete_selected:  "ลบที่เลือก",
    cart_shop_recommend:   "ร้านค้าแนะนำ",
    cart_chat_shop:        "แชทกับร้านค้า",
    cart_out_of_stock:     "สินค้าหมด",
    cart_shop_voucher:     "คูปองร้านค้า: ลดเพิ่ม ฿30 เมื่อซื้อขั้นต่ำ ฿300",
    cart_code:             "โค้ด",
    cart_summary:          "สรุปคำสั่งซื้อ",
    cart_selected_items:   "สินค้าที่เลือก",
    cart_subtotal:         "ยอดรวมสินค้า",
    cart_discount:         "ส่วนลด",
    cart_shipping:         "ค่าจัดส่ง",
    cart_grand_total:      "มูลค่าสินค้ารวม",
    cart_protected:        "การซื้อของคุณได้รับการคุ้มครอง",
    cart_checkout:         "สั่งซื้อสินค้า",
    cart_continue:         "ช้อปปิ้งต่อ",
    cart_removed:          "ลบสินค้าออกจากรถเข็นแล้ว",
    cart_removed_selected: "ลบสินค้าที่เลือกแล้ว",
    cart_coupon_applied:   "ใช้โค้ดส่วนลดสำเร็จ!",
    cart_coupon_removed:   "ลบโค้ดส่วนลดแล้ว",
    cart_discount_amount:  "ลด ฿100.00",

    /* ===== payment ===== */
    pay_title:             "ชำระเงิน",
    pay_empty:             "ไม่มีสินค้าในตะกร้า",
    pay_shop_now:          "ช้อปเลย",
    pay_address_title:     "ที่อยู่ในการจัดส่ง",
    pay_change:            "เปลี่ยน",
    pay_default_address:   "ที่อยู่หลัก",
    pay_add_new_address:   "+ เพิ่มที่อยู่ใหม่",
    pay_shipping_title:    "ตัวเลือกการจัดส่ง",
    pay_shipping_eta:      "จะได้รับภายใน 18 ก.พ. - 20 ก.พ.",
    pay_method_title:      "ช่องชำระเงิน",
    pay_method_promptpay:  "พร้อมเพย์ PromptPay",
    pay_method_promptpay_desc:"แสกน QR Code ชำระเงิน",
    pay_method_bank:       "บัญชีธนาคาร",
    pay_method_bank_desc:  "โอนเงินผ่านบัญชีธนาคารร้านค้า",
    pay_method_credit:     "บัตรเครดิต/บัตรเดบิต",
    pay_method_credit_desc:"ชำระเงินผ่านบัตรเครดิต/บัตรเดบิต",
    pay_method_cod:        "ชำระเงินปลายทาง",
    pay_method_cod_desc:   "ชำระเงินเมื่อได้รับสินค้าแล้ว",
    pay_summary:           "สรุปคำสั่งซื้อ",
    pay_option:            "ตัวเลือก 1",
    pay_qty_text:          "จำนวน",
    pay_coupon:            "โค้ดส่วนลด",
    pay_subtotal:          "ยอดรวมสินค้า",
    pay_discount:          "ส่วนลด",
    pay_vat:               "VAT 7%",
    pay_shipping:          "ค่าจัดส่ง",
    pay_grand_total:       "ยอดที่ต้องชำระ",
    pay_confirm:           "ยืนยันคำสั่งซื้อ",

    /* ===== verify payment ===== */
    vp_title:              "รอชำระเงิน",
    vp_subtitle:           "กรุณาชำระเงินภายใน 24 ชม. เพื่อไม่ให้คำสั่งซื้อของคุณถูกยกเลิก",
    vp_amount:             "ยอดที่ต้องชำระ",
    vp_promptpay:          "ชำระด้วยพร้อมเพย์ PromptPay",
    vp_remaining:          "เหลือเวลาชำระเงิน 24:00:00 ชั่วโมง",
    vp_receiver:           "ชื่อผู้รับเงิน:",
    vp_receiver_name:      "ทดสอบ ระบบ",
    vp_promptpay_no:       "หมายเลขพร้อมเพย์:",
    vp_warning:            "สำคัญ: กรุณาอย่าชำระ QR Code นี้กับผู้อื่น และตรวจสอบจำนวนเงินให้ถูกต้องก่อนชำระเงิน",
    vp_view_order:         "ดูรายละเอียดคำสั่งซื้อ",
    vp_all_orders:         "คำสั่งซื้อทั้งหมด",
    vp_continue_shop:      "ช้อปปิ้งต่อ",
    vp_method:             "วิธีชำระเงิน:",
    vp_amount_label:       "จำนวนเงิน:",
    vp_status:             "สถานะการชำระเงิน:",
    vp_pending:            "รอชำระเงิน",
    vp_upload_title:       "อัพโหลดหลักฐานการชำระเงิน",
    vp_upload_sub:         "กรุณาอัพโหลดสลิปหรือหลักฐานการโอนเงินเพื่อให้เราตรวจสอบและดำเนินการจัดส่งสินค้า",
    vp_upload_choose:      "เลือกไฟล์รูปภาพ (JPG, PNG)",
    vp_not_found:          "ไม่พบคำสั่งซื้อ",

    /* ===== orders ===== */
    orders_title:          "คำสั่งซื้อของฉัน",
    orders_tab_all:        "ทั้งหมด",
    orders_tab_pending:    "รอชำระเงิน",
    orders_tab_preparing:  "กำลังจัดเตรียม",
    orders_tab_shipped:    "จัดส่งแล้ว",
    orders_tab_delivered:  "ได้รับสินค้าแล้ว",
    orders_tab_completed:  "สำเร็จ",
    orders_tab_cancelled:  "ยกเลิก",
    orders_status_pending_payment: "รอชำระเงิน",
    orders_status_pending_verify:  "รอตรวจสอบ",
    orders_status_preparing:       "กำลังจัดเตรียม",
    orders_status_shipped:         "จัดส่งแล้ว",
    orders_status_delivered:       "รับสินค้าแล้ว",
    orders_status_completed:       "สำเร็จ",
    orders_status_cancelled:       "ยกเลิก",
    orders_empty:          "ไม่มีคำสั่งซื้อ",
    orders_shop_now:       "ไปช้อปปิ้ง",
    orders_view_details:   "ดูรายละเอียด",
    orders_view_all_items: "ดูทั้งหมด",
    orders_status_label:   "สถานะคำสั่งซื้อ",
    orders_tracking_no:    "หมายเลขพัสดุ:",
    orders_tracking_copied:"คัดลอกหมายเลขพัสดุแล้ว",
    orders_total_label:    "รวมการสั่งซื้อ:",
    orders_btn_cancel:     "ยกเลิก",
    orders_btn_pay:        "ชำระเงิน",
    orders_btn_edit:       "แก้ไขข้อมูล",
    orders_btn_contact:    "ติดต่อร้าน",
    orders_btn_confirm_received:"ยืนยันรับสินค้า",
    orders_btn_complaint:  "แจ้งปัญหาสินค้า",
    orders_btn_review:     "รีวิวสินค้า",
    orders_btn_buy_again:  "ซื้ออีกครั้ง",
    orders_btn_rebuy:      "ซื้อใหม่",
    orders_cancelled_toast:"ยกเลิกคำสั่งซื้อแล้ว",
    orders_received_toast: "ยืนยันรับสินค้าแล้ว!",
    orders_id_copied:      "คัดลอกหมายเลขคำสั่งซื้อแล้ว",
    review_title:          "รีวิวสินค้า",
    review_tap_star:       "แตะดาวเพื่อให้คะแนน",
    review_rating_1:       "แย่มาก",
    review_rating_2:       "ไม่ดี",
    review_rating_3:       "ปกติ",
    review_rating_4:       "ดี",
    review_rating_5:       "ดีมาก",
    review_tag_good:       "สินค้าดี",
    review_tag_fast:       "ส่งเร็ว",
    review_tag_package:    "แพ็คเกจดี",
    review_tag_worth:      "คุ้มค่า",
    review_tag_accurate:   "ตรงปก",
    review_placeholder:    "เขียนรีวิวของคุณ...",
    review_submit:         "ส่งรีวิว",
    review_thanks:         "ขอบคุณสำหรับรีวิว!",
    refund_title:          "ขอคืนเงิน/คืนสินค้า",
    refund_subtitle:       "เลือกเหตุผลในการขอคืนเงิน",
    refund_reason_desc:    "สินค้าไม่ตรงตามคำอธิบาย",
    refund_reason_damaged: "สินค้าชำรุด/เสียหาย",
    refund_reason_wrong:   "ได้รับสินค้าผิดชิ้น",
    refund_reason_qty:     "สินค้าไม่ครบตามจำนวน",
    refund_reason_change:  "เปลี่ยนใจ",
    refund_reason_other:   "อื่นๆ",
    refund_detail_ph:      "รายละเอียดเพิ่มเติม (ไม่บังคับ)",
    refund_submit:         "ส่งคำขอ",
    refund_success:        "ส่งคำขอคืนเงินเรียบร้อย",
    refund_success_desc:   "ทีมงานจะตรวจสอบภายใน 1-3 วันทำการ",
    complaint_select_title:"โปรดระบุปัญหาที่คุณพบ",
    complaint_order_label: "คำสั่งซื้อ:",
    complaint_type_damaged:"สินค้าเสียหาย",
    complaint_type_damaged_desc:"สินค้าที่มีรอยแตก บุบ หรือชำรุดจากการขนส่ง",
    complaint_type_wrong:  "สินค้าไม่ตรงตามที่สั่ง",
    complaint_type_wrong_desc:"ได้รับสินค้าผิดรายการจากที่สั่ง",
    complaint_type_return: "ต้องการคืนสินค้า",
    complaint_type_return_desc:"ส่งคืนสินค้าและรับเป็นเครดิตหรือสินค้าใหม่",
    complaint_type_refund: "ต้องการขอเงินคืน",
    complaint_type_refund_desc:"ต้องการขอคืนเงินจากการสั่งซื้อ",

    /* ===== blog ===== */
    blog_title:            "สาระความรู้ทั้งหมด",
    blog_articles:         "บทความ",
    blog_videos:           "วีดีโอ",
    blog_read_more:        "อ่านเพิ่มเติม",
    blog_share:            "แชร์บทความ",
    blog_views:            "จำนวนผู้เข้าชม",
    blog_copy_link:        "คัดลอกลิงก์แล้ว!",

    /* ===== coupon ===== */
    coupon_title:          "คูปอง METAHERB",
    coupon_tab_all:        "ทั้งหมด",
    coupon_tab_discount:   "ส่วนลด",
    coupon_tab_freeship:   "ส่งฟรี",
    coupon_min:            "ขั้นต่ำ",
    coupon_terms:          "เงื่อนไข",
    coupon_collected:      "เก็บแล้ว",
    coupon_collect:        "เก็บ",
    coupon_received:       "คุณได้รับคูปองแล้ว!",
    coupon_discount_label: "โค้ดส่วนลด",
    coupon_free_label:     "โค้ดส่งฟรี",
    coupon_express:        "ส่งด่วน",
    coupon_all_shops:      "ทุกร้านค้า",
    my_coupons_title:      "คูปองของฉัน",
    my_coupons_collect_more:"เก็บคูปองเพิ่มเติม",
    my_coupons_tab_used:   "ใช้แล้ว",
    my_coupons_tab_expired:"หมดอายุ",
    my_coupons_use:        "ใช้งาน",
    my_coupons_expired:    "หมดอายุแล้ว",
    my_coupons_use_toast:  "เลือกใช้คูปองแล้ว!",
    my_coupons_empty:      "ยังไม่มีคูปองในหมวดนี้",
    my_coupons_empty_sub:  "ไปเก็บคูปองเพิ่มได้เลย!",
    my_coupons_go:         "เก็บคูปอง",

    /* ===== wishlist ===== */
    wishlist_title:        "สินค้าที่ชอบ",
    wishlist_empty:        "ยังไม่มีสินค้าที่ชอบ",
    wishlist_shop:         "ไปช้อปปิ้ง",
    wishlist_add_cart:     "เพิ่มลงรถเข็น",
    wishlist_added_cart:   "เพิ่มลงรถเข็นแล้ว",
    wishlist_count_unit:   "รายการ",

    /* ===== about ===== */
    about_welcome:         "ยินดีต้อนรับ",
    about_hero_1:          "จากพืชพรรณ",
    about_hero_2:          "สู่ผลิตภัณฑ์",
    about_hero_3:          "เมต้าเฮิร์บ",
    about_subtitle:        "แม้เป็นสมุนไพรที่หายากแต่เมต้าเฮิร์บ",
    about_subtitle2:       "สามารถคัดสรรและจัดหาให้คุณได้",
    about_cta_shop:        "เลือกซื้อได้ที่",
    about_cta_mission:     "พันธกิจของเรา",
    about_scroll:          "เลื่อนเพื่อดูเนื้อหา",
    about_our_story:       "เรื่องราวของเรา",
    about_story_h1:        "ผลผลิตจากเกษตรกร",
    about_story_h2:        "สู่ทุกบ้านทั่วไทย",
    about_story_sub:       "เราเป็นผู้นำด้านสมุนไพรคุณภาพ เพื่อสุขภาพที่ยั่งยืนที่เมต้าเฮิร์บ",
    about_feat1_title:     "ต้นกำเนิดจากธรรมชาติแท้",
    about_feat1_desc:      "สมุนไพรทุกชนิดของเราได้รับการปลูกและดูแลโดยเกษตรกรท้องถิ่น บนพื้นที่กว่า 120 ไร่ที่ดอยแม่สลอง เชียงราย ภายใต้มาตรฐานเกษตรอินทรีย์ที่เคร่งครัด",
    about_feat2_title:     "ภูมิปัญญาดั้งเดิมสู่นวัตกรรมใหม่",
    about_feat2_desc:      "เราผสมผสานองค์ความรู้สมุนไพรไทยโบราณที่สืบทอดมากว่า 200 ปี เข้ากับเทคโนโลยีการผลิตสมัยใหม่ เพื่อให้ได้ผลิตภัณฑ์ที่มีประสิทธิภาพสูงสุดและปลอดภัย",
    about_feat3_title:     "การรับรองมาตรฐานระดับสากล",
    about_feat3_desc:      "ผลิตภัณฑ์ทุกชิ้นผ่านการตรวจสอบคุณภาพและได้รับการรับรองจาก อย. Thailand, Organic Thailand และ ISO 22000 ก่อนส่งถึงมือลูกค้า",
    about_trust_h1:        "ความไว้วางใจที่",
    about_trust_h2:        "สร้างมาจากมาตรฐาน",
    about_product_featured:"ผลิตภัณฑ์เด่นของเรา",
    about_tag_bestseller:  "ขายดีอันดับ 1",
    about_tag_new:         "สินค้าใหม่",
    about_tag_popular:     "ยอดนิยม",
    about_mission_h1:      "พันธกิจและวิสัยทัศน์",
    about_mission_h2:      "เราทำงานเพื่ออะไร ?",
    about_mission_quote:   '"เป็นผู้นำสมุนไพรไทยสู่ตลาดโลก"',
    about_mission_desc:    "มุ่งมั่นที่จะเป็นผู้นำในการนำเสนอสมุนไพรไทยคุณภาพสู่ผู้บริโภค เพื่อสุขภาพที่ดีและยั่งยืน",
    about_stat_years:      "ปีแห่งประสบการณ์",
    about_stat_farm:       "ไร่แปลงเกษตรอินทรีย์",
    about_stat_products:   "ผลิตภัณฑ์สมุนไพร",
    about_stat_customers:  "ลูกค้าทั่วไทย",
    about_contact_h1:      "พูดคุยกับเรา",
    about_contact_h2:      "ได้ทุกช่องทาง",
    about_contact_sub:     "เราพร้อมให้คำปรึกษาเรื่องสมุนไพรและผลิตภัณฑ์ทุกชนิด ติดต่อเราได้ผ่านช่องทางที่คุณสะดวก",
    about_contact_info:    "ข้อมูลการติดต่อ",
    about_phone:           "โทรศัพท์",
    about_phone_hours:     "จันทร์-ศุกร์: 08.30 - 17.30",
    about_email:           "อีเมล",
    about_email_reply:     "ตอบกลับภายใน 24 ชั่วโมง",
    about_address:         "ที่อยู่",
    about_follow_us:       "ติดตามเราบนโซเชียล",
    about_send_message:    "ส่งข้อความถึงเรา",
    about_form_sub:        "กรอกแบบฟอร์มด้านล่าง",
    about_form_name:       "ชื่อ-นามสกุล",
    about_form_name_ph:    "ชื่อของคุณ",
    about_form_email:      "อีเมล",
    about_form_email_ph:   "อีเมลของคุณ",
    about_form_subject:    "หัวข้อ",
    about_form_subject_ph: "หัวข้อการติดต่อ",
    about_form_message:    "ข้อความ",
    about_form_message_ph: "พิมพ์ข้อความของคุณ...",
    about_form_send:       "ส่งข้อความ",
    about_form_success:    "ส่งข้อความเรียบร้อยแล้ว!",
    about_form_success_desc:"ทีมงานจะติดต่อกลับภายใน 24 ชั่วโมง",

    /* ===== account ===== */
    account_title:         "บัญชีของฉัน",
    account_role:          "บทบาท",
    account_role_user:     "ผู้ใช้งาน",
    account_role_owner:    "เจ้าของร้าน",
    account_role_admin:    "ผู้ดูแลระบบ",
    account_change_avatar: "เปลี่ยนรูปโปรไฟล์",
    account_avatar_sub:    "รองรับไฟล์: JPEG, PNG, GIF, WebP",
    account_avatar_size:   "ขนาดไม่เกิน: 5MB",
    account_user_info:     "ข้อมูลผู้ใช้",
    account_edit:          "แก้ไข",
    account_username:      "ชื่อผู้ใช้",
    account_email:         "อีเมล",
    account_phone:         "เบอร์โทรศัพท์",
    account_password:      "รหัสผ่านของคุณ",
    account_change_pw:     "เปลี่ยนรหัสผ่าน",
    account_password_label:"รหัสผ่าน",
    account_current_pw:    "รหัสผ่านปัจจุบัน",
    account_new_pw:        "รหัสผ่านใหม่",
    account_confirm_pw:    "ยืนยันรหัสผ่านใหม่",
    account_current_pw_ph: "กรอกรหัสผ่านปัจจุบัน",
    account_new_pw_ph:     "กรอกรหัสผ่านใหม่",
    account_confirm_pw_ph: "กรอกรหัสผ่านใหม่อีกครั้ง",
    account_pw_mismatch:   "รหัสผ่านใหม่ไม่ตรงกัน",
    account_settings:      "การตั้งค่า",
    account_about_notif:   "เกี่ยวกับการแจ้งเตือน",
    account_notif_orders:  "การแจ้งเตือนการสั่งซื้อ",
    account_notif_promo:   "การแจ้งเตือนโปรโมชั่น",
    account_notif_msg:     "การแจ้งเตือนข้อความ",
    account_notif_status:  "การแจ้งเตือนสถานะสินค้า",
    account_saved:         "บันทึกข้อมูลเรียบร้อย",
    account_pw_changed:    "เปลี่ยนรหัสผ่านเรียบร้อย",

    /* ===== address ===== */
    address_title:         "ที่อยู่จัดส่ง",
    address_add_new:       "เพิ่มที่อยู่ใหม่",
    address_default:       "ที่อยู่หลัก",
    address_set_default:   "ตั้งเป็นหลัก",
    address_edit_title:    "แก้ไขที่อยู่",
    address_add_title:     "เพิ่มที่อยู่ใหม่",
    address_first_name:    "ชื่อ",
    address_last_name:     "นามสกุล",
    address_first_name_ph: "ระบุชื่อผู้รับ",
    address_last_name_ph:  "นามสกุล",
    address_phone:         "เบอร์โทรศัพท์",
    address_phone_ph:      "ระบุเบอร์โทรศัพท์",
    address_addr_label:    "ที่อยู่",
    address_addr_ph:       "ระบุรหัสไปรษณีย์ หรือ ตำบล / แขวง",
    address_detail:        "รายละเอียดที่อยู่",
    address_detail_ph:     "บ้านเลขที่, หมู่ที่, ชื่ออาคาร, ซอย ถนน",
    address_set_default_toggle:"ตั้งเป็นที่อยู่หลัก",
    address_save:          "บันทึกที่อยู่",
    address_add:           "เพิ่มที่อยู่",
    address_required:      "กรุณากรอกข้อมูลที่จำเป็นให้ครบ",
    address_set_default_toast:"ตั้งเป็นที่อยู่หลักแล้ว",
    address_deleted:       "ลบที่อยู่แล้ว",
    address_edited:        "แก้ไขที่อยู่แล้ว",
    address_added:         "เพิ่มที่อยู่ใหม่แล้ว",

    /* ===== complaint form/status ===== */
    cf_reason_title:       "สาเหตุการร้องเรียน",
    cf_return_addr_title:  "ที่อยู่สำหรับรับสินค้าใหม่ / คืนสินค้า",
    cf_shipping_addr:      "ที่อยู่จัดส่ง",
    cf_default:            "ที่อยู่หลัก",
    cf_evidence:           "หลักฐานรูปภาพ",
    cf_evidence_sub:       "อัปโหลดรูปภาพสินค้า บรรจุภัณฑ์ หรือหลักฐานที่เกี่ยวข้อง (JPEG, PNG, WebP, ไม่เกิน 5MB/ไฟล์)",
    cf_upload_click:       "คลิกเพื่ออัปโหลดรูปภาพ",
    cf_upload_drag:        "หรือลากไฟล์มาวางที่นี่",
    cf_upload_choose:      "เลือกไฟล์",
    cf_more_detail:        "รายละเอียดเพิ่มเติม",
    cf_more_detail_ph:     "อธิบายปัญหาที่พบโดยละเอียด...",
    cf_refund_items:       "สินค้าที่ต้องการขอคืนเงิน",
    cf_refund_details:     "รายละเอียดการคืนเงิน",
    cf_refund_amount:      "ยอดเงินคืน",
    cf_refund_channel:     "ช่องทางคืนเงิน",
    cf_refund_bank:        "ธนาคารทหารไทยธนชาต [*1234]",
    cf_email:              "อีเมล",
    cf_actual_refund:      "จำนวนเงินคืนตามจริง",
    cf_confirm:            "ยืนยัน",
    cf_detail_required:    "กรุณากรอกรายละเอียดปัญหา",
    cf_image_uploaded:     "อัปโหลดรูปภาพสำเร็จ",
    cf_submitted:          "ส่งคำร้องเรียนเรียบร้อยแล้ว",
    cs_complaint_info:     "ข้อมูลการร้องเรียน",
    cs_order_no:           "เลขที่คำสั่งซื้อ",
    cs_product:            "สินค้า",
    cs_refund_amt:         "ยอดเงินคืน",
    cs_refund_channel:     "ช่องทางคืนเงิน",
    cs_date:               "วันที่แจ้ง",
    cs_type:               "ประเภท",
    cs_email:              "อีเมล",
    cs_details:            "รายละเอียด",
    cs_shop_msg:           "ข้อความจากร้านค้า",
    cs_progress:           "ความคืบหน้า",
    cs_pending:            "รอดำเนินการ",
    cs_help:               "ต้องการความช่วยเหลือ?",
    cs_help_sub:           "หากมีคำถามเพิ่มเติม ติดต่อเราได้ที่:",
    cs_help_hours:         "จันทร์ – ศุกร์ 08:30 – 17:30 น.",
    cs_step1_title:        "ส่งคำร้องเรียน",
    cs_step1_desc:         "ระบบได้รับคำร้องเรียนของคุณแล้ว",
    cs_step2_title:        "ตรวจสอบข้อมูล",
    cs_step2_desc:         "ทีมงานกำลังตรวจสอบหลักฐานและข้อมูล",
    cs_step3_title:        "อนุมัติและดำเนินการ",
    cs_step3_desc:         "อยู่ระหว่างจัดส่งสินค้าทดแทน",
    cs_step4_title:        "จัดส่งสินค้าทดแทน",
    cs_step4_desc:         "ส่งสินค้าทดแทนให้ลูกค้า",
    cs_step5_title:        "เสร็จสิ้น",
    cs_step5_desc:         "ปิดคำร้องเรียน",
    cs_shop_msg_text:      "ขออภัยในความไม่สะดวก ทางร้านได้ทำการโอนเงินคืนเป็นจำนวน xx.xx บาท ไปยังบัญชี x123 Visa แล้ว",
    cs_sample_detail:      "กล่องสินค้าบุบเสียหายอย่างหนัก ผลิตภัณฑ์ด้านในแตกออกและหกเลอะ ไม่สามารถใช้งานได้",

    /* ===== shop profile ===== */
    shop_chat:             "แชทกับร้าน",
    shop_follow:           "ติดตาม",
    shop_followed:         "ติดตามแล้ว",
    shop_products:         "สินค้า",
    shop_followers:        "ผู้ติดตาม",
    shop_response_rate:    "อัตราตอบกลับ",
    shop_response_time:    "เวลาตอบกลับ",
    shop_rating:           "เรตติ้ง",
    shop_joined:           "เข้าร่วม",
    shop_tab_home:         "หน้าหลัก",
    shop_tab_products:     "สินค้า",
    shop_tab_categories:   "หมวดหมู่",
    shop_tab_about:        "เกี่ยวกับร้าน",
    shop_new_arrivals:     "สินค้ามาใหม่",
    shop_bestsellers:      "สินค้าขายดี",
    shop_all_products:     "สินค้าทั้งหมด",

    /* ===== settings ===== */
    settings_title:        "การตั้งค่า",
    settings_general:      "ทั่วไป",
    settings_language:     "ภาษา",
    settings_notifications:"การแจ้งเตือน",
    settings_privacy:      "ความเป็นส่วนตัว",
    settings_security:     "ความปลอดภัย",
    settings_help:         "ช่วยเหลือ",
    settings_logout:       "ออกจากระบบ",
    settings_logout_confirm:"คุณต้องการออกจากระบบใช่หรือไม่?",

    /* ===== misc / shared ===== */
    chat_typing:           "กำลังพิมพ์...",
    chat_placeholder:      "พิมพ์ข้อความ...",
    chat_send:             "ส่ง",
    chat_title:            "แชทกับร้านค้า",
    chat_online:           "ออนไลน์",
    chat_offline:          "ออฟไลน์",
    chat_start_with:       "เริ่มสนทนากับ",
    chat_start_default:    "เริ่มสนทนา...",
    chat_quick_q1:         "สอบถามสินค้า",
    chat_quick_q2:         "สถานะคำสั่งซื้อ",
    chat_quick_q3:         "ขอใบเสร็จ",
    chat_quick_q4:         "แจ้งปัญหา",
    notif_title:           "การแจ้งเตือน",
    notif_empty:           "ไม่มีการแจ้งเตือน",
    notif_mark_all:        "ทำเครื่องหมายว่าอ่านแล้วทั้งหมด",
  },

  en: {
    /* ===== appbar / common ===== */
    menu_home:          "Home",
    menu_products:      "Products",
    menu_market:        "Herbal Market",
    menu_blog:          "Articles",
    menu_about:         "About",
    button_login:       "Sign in",
    search_placeholder: "Search products, herbs, brands...",
    search_button:      "Search",
    search_aria:        "Search",
    close_aria:         "Close",

    common_back:           "Back",
    common_cancel:         "Cancel",
    common_save:           "Save",
    common_confirm:        "Confirm",
    common_edit:           "Edit",
    common_delete:         "Delete",
    common_change:         "Change",
    common_loading:        "Loading...",
    common_or:             "or",
    common_view_all:       "View all",
    common_view_details:   "View details",
    common_read_more:      "Read more",
    common_required:       "Please fill in all required fields",
    common_yes:            "Yes",
    common_no:             "No",
    common_close:          "Close",
    common_submit:         "Submit",
    common_send:           "Send",
    common_continue:       "Continue",
    common_shop_now:       "Shop now",
    common_continue_shop:  "Continue shopping",
    common_apply:          "Apply",
    common_items:          "items",
    common_pieces:         "pcs",
    common_pcs:            "pcs",
    common_qty:            "Qty",
    common_total:          "Total",
    common_subtotal:       "Subtotal",
    common_discount:       "Discount",
    common_shipping:       "Shipping",
    common_free:           "Free",
    common_sort:           "Sort by",
    common_sort_desc:      "Price: High to Low",
    common_sort_asc:       "Price: Low to High",
    common_filter:         "Filter",
    common_reset_filter:   "Reset filters",
    common_prev_page:      "Previous page",
    common_next_page:      "Next page",
    common_no_orders:      "No orders",
    common_not_found:      "Not found",
    common_optional:       "optional",
    common_required_mark:  "*",
    common_search_results: "Search results",
    common_results_found:  "Found",

    login_welcome:         "Welcome back",
    login_subtitle:        "Take care of your health with curated herbal products",
    login_subtitle2:       "Shop online now at Metaherb",
    login_email_label:     "Email or username",
    login_email_ph:        "Enter your email or username",
    login_password_label:  "Password",
    login_password_ph:     "Enter your password",
    login_forgot:          "Forgot password?",
    login_demo:            "Demo account (tap to auto-fill):",
    login_button:          "Sign in",
    login_no_account:      "Don't have an account?",
    login_register_link:   "Sign up",
    login_invalid:         "Invalid email or password",
    register_title:        "Create account",
    register_role_label:   "Account type",
    register_role_user:    "Buyer",
    register_role_owner:   "Seller",
    register_username_label:"Username",
    register_username_ph:  "Enter username",
    register_password_label:"Password",
    register_password_ph:  "At least 8 characters",
    register_email_label:  "Email",
    register_email_ph:     "Enter your email",
    register_phone_label:  "Phone number",
    register_phone_ph:     "Enter phone number",
    register_accept:       "I accept",
    register_terms:        "the Meta Herb Terms of Service",
    register_and:          "and",
    register_privacy:      "Privacy Policy",
    register_button:       "Sign up",
    register_has_account:  "Already have an account?",
    register_login_link:   "Sign in",
    register_password_min: "Password must be at least 8 characters",
    register_accept_terms: "Please accept the terms",

    home_recommended:      "Recommended",
    home_flash_sale:       "Flash Sale",
    home_articles:         "Featured articles",
    home_videos:           "Featured videos",
    home_recommended_tag:  "Featured",
    home_discount_prefix:  "-",
    cat_herb:              "Herbs",
    cat_food:              "Food",
    cat_medicine:          "Medicine",
    cat_aroma:             "Aroma",
    cat_beauty:            "Beauty",
    cat_giftset:           "Gift sets",
    cat_tea:               "Herbal tea",
    cat_supplement:        "Supplements",
    cat_oil:               "Essential oils",

    products_title:        "All products",
    products_filter:       "Filters",
    products_category:     "Category",
    products_type:         "Product type",
    products_price_range:  "Price range",
    products_all:          "All",
    products_type_flash:   "Flash Sale",
    products_type_promo:   "Promotion",
    products_type_rec:     "Recommended",
    products_showing:      "Showing",
    products_of:           "of",
    products_results:      "items",

    pd_back_to_products:   "Back to products",
    pd_in_stock:           "In stock",
    pd_out_of_stock:       "Out of stock",
    pd_quantity:           "Quantity",
    pd_available:          "available",
    pd_options:            "Options",
    pd_select_option:      "Select option",
    pd_add_to_cart:        "Add to cart",
    pd_buy_now:            "Buy now",
    pd_chat:               "Chat with seller",
    pd_description:        "Description",
    pd_specs:              "Specifications",
    pd_reviews:            "Reviews",
    pd_related:            "Related products",
    pd_sold:               "sold",
    pd_rating:             "Rating",
    pd_shop:               "Shop",
    pd_visit_shop:         "Visit shop",
    pd_added_to_cart:      "Added to cart",
    pd_added_to_wishlist:  "Added to wishlist",
    pd_removed_from_wishlist:"Removed from wishlist",
    pd_select_option_first:"Please select an option",
    pd_share:              "Share",
    pd_copy_link:          "Link copied!",
    pd_all_reviews:        "All reviews",
    pd_write_review:       "Write a review",
    pd_filter_reviews:     "Filter reviews",
    pd_with_image:         "With photos",
    pd_specifications:     "Specifications",
    pd_no_reviews:         "No reviews yet",
    pd_price:              "Price",
    pd_options_label:      "Options",
    pd_quantity_label:     "Quantity",
    pd_remaining:          "Only",
    pd_add_to_cart_btn:    "Add to cart",
    pd_added_btn:          "Added!",
    pd_buy_now_btn:        "Buy now",
    pd_product_details:    "Product details",
    pd_product_specs:      "Specifications",
    pd_weight:             "Net weight:",
    pd_type:               "Type:",
    pd_sku:                "SKU:",
    pd_format:             "Format:",
    pd_shop_items:         "Products",
    pd_shop_items_unit:    "items",
    pd_shop_rating:        "Shop rating",
    pd_all_ratings:        "Total ratings 100",
    pd_loved_items:        "Liked",
    pd_view_shop:          "View shop",
    pd_ask_shop:           "Ask shop",
    pd_review_option_prefix:"Option:",
    pd_recommended_for_you:"Recommended for you",
    pd_all_filter:         "All",
    pd_view_review_image:  "View review image",
    pd_prev:               "Previous",
    pd_next:               "Next",

    cart_title:            "Cart",
    cart_empty:            "Your cart is empty",
    cart_empty_sub:        "Add your favorite products to the cart",
    cart_select_all:       "Select all",
    cart_delete_selected:  "Delete selected",
    cart_shop_recommend:   "Recommended shop",
    cart_chat_shop:        "Chat with shop",
    cart_out_of_stock:     "Out of stock",
    cart_shop_voucher:     "Shop voucher: ฿30 off when you spend ฿300+",
    cart_code:             "Code",
    cart_summary:          "Order summary",
    cart_selected_items:   "Selected items",
    cart_subtotal:         "Subtotal",
    cart_discount:         "Discount",
    cart_shipping:         "Shipping",
    cart_grand_total:      "Grand total",
    cart_protected:        "Your purchase is protected",
    cart_checkout:         "Checkout",
    cart_continue:         "Continue shopping",
    cart_removed:          "Item removed from cart",
    cart_removed_selected: "Selected items removed",
    cart_coupon_applied:   "Coupon applied successfully!",
    cart_coupon_removed:   "Coupon removed",
    cart_discount_amount:  "Saved ฿100.00",

    pay_title:             "Checkout",
    pay_empty:             "Your cart is empty",
    pay_shop_now:          "Shop now",
    pay_address_title:     "Shipping address",
    pay_change:            "Change",
    pay_default_address:   "Default",
    pay_add_new_address:   "+ Add new address",
    pay_shipping_title:    "Shipping options",
    pay_shipping_eta:      "Arrives Feb 18 - Feb 20",
    pay_method_title:      "Payment method",
    pay_method_promptpay:  "PromptPay",
    pay_method_promptpay_desc:"Scan QR code to pay",
    pay_method_bank:       "Bank transfer",
    pay_method_bank_desc:  "Transfer to shop's bank account",
    pay_method_credit:     "Credit / Debit card",
    pay_method_credit_desc:"Pay by credit or debit card",
    pay_method_cod:        "Cash on delivery",
    pay_method_cod_desc:   "Pay when you receive the goods",
    pay_summary:           "Order summary",
    pay_option:            "Option 1",
    pay_qty_text:          "Qty",
    pay_coupon:            "Coupon",
    pay_subtotal:          "Subtotal",
    pay_discount:          "Discount",
    pay_vat:               "VAT 7%",
    pay_shipping:          "Shipping",
    pay_grand_total:       "Total to pay",
    pay_confirm:           "Place order",

    vp_title:              "Awaiting payment",
    vp_subtitle:           "Please pay within 24 hours to avoid cancellation",
    vp_amount:             "Amount to pay",
    vp_promptpay:          "Pay with PromptPay",
    vp_remaining:          "Time remaining 24:00:00",
    vp_receiver:           "Receiver:",
    vp_receiver_name:      "Test System",
    vp_promptpay_no:       "PromptPay number:",
    vp_warning:            "Important: Do not share this QR code with others and verify the amount before paying",
    vp_view_order:         "View order details",
    vp_all_orders:         "All orders",
    vp_continue_shop:      "Continue shopping",
    vp_method:             "Payment method:",
    vp_amount_label:       "Amount:",
    vp_status:             "Payment status:",
    vp_pending:            "Awaiting payment",
    vp_upload_title:       "Upload payment proof",
    vp_upload_sub:         "Please upload your transfer slip so we can verify and ship your order",
    vp_upload_choose:      "Choose image file (JPG, PNG)",
    vp_not_found:          "Order not found",

    orders_title:          "My orders",
    orders_tab_all:        "All",
    orders_tab_pending:    "Awaiting payment",
    orders_tab_preparing:  "Preparing",
    orders_tab_shipped:    "Shipped",
    orders_tab_delivered:  "Delivered",
    orders_tab_completed:  "Completed",
    orders_tab_cancelled:  "Cancelled",
    orders_status_pending_payment: "Awaiting payment",
    orders_status_pending_verify:  "Verifying",
    orders_status_preparing:       "Preparing",
    orders_status_shipped:         "Shipped",
    orders_status_delivered:       "Delivered",
    orders_status_completed:       "Completed",
    orders_status_cancelled:       "Cancelled",
    orders_empty:          "No orders",
    orders_shop_now:       "Shop now",
    orders_view_details:   "View details",
    orders_view_all_items: "View all",
    orders_status_label:   "Order status",
    orders_tracking_no:    "Tracking no.:",
    orders_tracking_copied:"Tracking number copied",
    orders_total_label:    "Order total:",
    orders_btn_cancel:     "Cancel",
    orders_btn_pay:        "Pay now",
    orders_btn_edit:       "Edit info",
    orders_btn_contact:    "Contact shop",
    orders_btn_confirm_received:"Confirm receipt",
    orders_btn_complaint:  "Report issue",
    orders_btn_review:     "Review",
    orders_btn_buy_again:  "Buy again",
    orders_btn_rebuy:      "Buy again",
    orders_cancelled_toast:"Order cancelled",
    orders_received_toast: "Receipt confirmed!",
    orders_id_copied:      "Order ID copied",
    review_title:          "Review product",
    review_tap_star:       "Tap a star to rate",
    review_rating_1:       "Terrible",
    review_rating_2:       "Bad",
    review_rating_3:       "Okay",
    review_rating_4:       "Good",
    review_rating_5:       "Excellent",
    review_tag_good:       "Good product",
    review_tag_fast:       "Fast shipping",
    review_tag_package:    "Nice packaging",
    review_tag_worth:      "Worth it",
    review_tag_accurate:   "As described",
    review_placeholder:    "Write your review...",
    review_submit:         "Submit review",
    review_thanks:         "Thanks for your review!",
    refund_title:          "Request refund / return",
    refund_subtitle:       "Choose a reason for the refund",
    refund_reason_desc:    "Item not as described",
    refund_reason_damaged: "Damaged item",
    refund_reason_wrong:   "Wrong item received",
    refund_reason_qty:     "Quantity not correct",
    refund_reason_change:  "Changed my mind",
    refund_reason_other:   "Other",
    refund_detail_ph:      "Additional details (optional)",
    refund_submit:         "Submit request",
    refund_success:        "Refund request submitted",
    refund_success_desc:   "We'll review within 1-3 business days",
    complaint_select_title:"Please describe the issue",
    complaint_order_label: "Order:",
    complaint_type_damaged:"Damaged item",
    complaint_type_damaged_desc:"Cracked, dented or broken in transit",
    complaint_type_wrong:  "Wrong item",
    complaint_type_wrong_desc:"Received an item different from the order",
    complaint_type_return: "Return item",
    complaint_type_return_desc:"Return the item for credit or replacement",
    complaint_type_refund: "Request refund",
    complaint_type_refund_desc:"Request a refund for the order",

    blog_title:            "All articles",
    blog_articles:         "Articles",
    blog_videos:           "Videos",
    blog_read_more:        "Read more",
    blog_share:            "Share article",
    blog_views:            "Views",
    blog_copy_link:        "Link copied!",

    coupon_title:          "METAHERB Coupons",
    coupon_tab_all:        "All",
    coupon_tab_discount:   "Discount",
    coupon_tab_freeship:   "Free shipping",
    coupon_min:            "Min. spend",
    coupon_terms:          "Terms",
    coupon_collected:      "Collected",
    coupon_collect:        "Collect",
    coupon_received:       "Coupon collected!",
    coupon_discount_label: "Discount code",
    coupon_free_label:     "Free shipping",
    coupon_express:        "Express",
    coupon_all_shops:      "All shops",
    my_coupons_title:      "My coupons",
    my_coupons_collect_more:"Collect more coupons",
    my_coupons_tab_used:   "Used",
    my_coupons_tab_expired:"Expired",
    my_coupons_use:        "Use",
    my_coupons_expired:    "Expired",
    my_coupons_use_toast:  "Coupon selected!",
    my_coupons_empty:      "No coupons in this category",
    my_coupons_empty_sub:  "Go collect more coupons!",
    my_coupons_go:         "Collect coupons",

    wishlist_title:        "Wishlist",
    wishlist_empty:        "No favorite items yet",
    wishlist_shop:         "Shop now",
    wishlist_add_cart:     "Add to cart",
    wishlist_added_cart:   "Added to cart",
    wishlist_count_unit:   "items",

    about_welcome:         "Welcome",
    about_hero_1:          "From plant",
    about_hero_2:          "to product",
    about_hero_3:          "MetaHerb",
    about_subtitle:        "Even the rarest herbs — MetaHerb",
    about_subtitle2:       "sources and curates them for you",
    about_cta_shop:        "Shop now",
    about_cta_mission:     "Our mission",
    about_scroll:          "Scroll to see more",
    about_our_story:       "Our story",
    about_story_h1:        "From farmer's fields",
    about_story_h2:        "to every Thai home",
    about_story_sub:       "Leaders in quality herbs for sustainable health at MetaHerb",
    about_feat1_title:     "Pure natural origins",
    about_feat1_desc:      "All our herbs are grown and tended by local farmers on 120+ rai at Doi Mae Salong, Chiang Rai, under strict organic standards.",
    about_feat2_title:     "Ancient wisdom meets new innovation",
    about_feat2_desc:      "We combine 200+ years of traditional Thai herbal knowledge with modern production technology for maximum effectiveness and safety.",
    about_feat3_title:     "International certifications",
    about_feat3_desc:      "Every product is quality-checked and certified by Thai FDA, Organic Thailand and ISO 22000 before reaching customers.",
    about_trust_h1:        "Trust built",
    about_trust_h2:        "on standards",
    about_product_featured:"Our featured product",
    about_tag_bestseller:  "Best seller #1",
    about_tag_new:         "New",
    about_tag_popular:     "Popular",
    about_mission_h1:      "Mission & vision",
    about_mission_h2:      "What we work for",
    about_mission_quote:   '"Leading Thai herbs to the world market"',
    about_mission_desc:    "Committed to bringing quality Thai herbs to consumers for sustainable wellness.",
    about_stat_years:      "Years of experience",
    about_stat_farm:       "Rai of organic farm",
    about_stat_products:   "Herbal products",
    about_stat_customers:  "Customers in Thailand",
    about_contact_h1:      "Talk to us",
    about_contact_h2:      "on any channel",
    about_contact_sub:     "We're ready to advise on herbs and products. Reach us via your preferred channel.",
    about_contact_info:    "Contact info",
    about_phone:           "Phone",
    about_phone_hours:     "Mon-Fri: 08:30 - 17:30",
    about_email:           "Email",
    about_email_reply:     "Reply within 24 hours",
    about_address:         "Address",
    about_follow_us:       "Follow us on social",
    about_send_message:    "Send us a message",
    about_form_sub:        "Fill out the form below",
    about_form_name:       "Full name",
    about_form_name_ph:    "Your name",
    about_form_email:      "Email",
    about_form_email_ph:   "Your email",
    about_form_subject:    "Subject",
    about_form_subject_ph: "Subject of contact",
    about_form_message:    "Message",
    about_form_message_ph: "Type your message...",
    about_form_send:       "Send message",
    about_form_success:    "Message sent!",
    about_form_success_desc:"We'll get back to you within 24 hours",

    account_title:         "My account",
    account_role:          "Role",
    account_role_user:     "User",
    account_role_owner:    "Shop owner",
    account_role_admin:    "Admin",
    account_change_avatar: "Change avatar",
    account_avatar_sub:    "Supports: JPEG, PNG, GIF, WebP",
    account_avatar_size:   "Max size: 5MB",
    account_user_info:     "User info",
    account_edit:          "Edit",
    account_username:      "Username",
    account_email:         "Email",
    account_phone:         "Phone",
    account_password:      "Your password",
    account_change_pw:     "Change password",
    account_password_label:"Password",
    account_current_pw:    "Current password",
    account_new_pw:        "New password",
    account_confirm_pw:    "Confirm new password",
    account_current_pw_ph: "Enter current password",
    account_new_pw_ph:     "Enter new password",
    account_confirm_pw_ph: "Re-enter new password",
    account_pw_mismatch:   "New passwords do not match",
    account_settings:      "Settings",
    account_about_notif:   "About notifications",
    account_notif_orders:  "Order notifications",
    account_notif_promo:   "Promotion notifications",
    account_notif_msg:     "Message notifications",
    account_notif_status:  "Product status notifications",
    account_saved:         "Profile saved",
    account_pw_changed:    "Password changed",

    address_title:         "Shipping addresses",
    address_add_new:       "Add new address",
    address_default:       "Default",
    address_set_default:   "Set as default",
    address_edit_title:    "Edit address",
    address_add_title:     "Add new address",
    address_first_name:    "First name",
    address_last_name:     "Last name",
    address_first_name_ph: "Recipient first name",
    address_last_name_ph:  "Last name",
    address_phone:         "Phone",
    address_phone_ph:      "Enter phone number",
    address_addr_label:    "Address",
    address_addr_ph:       "Postcode, sub-district / khwaeng",
    address_detail:        "Address details",
    address_detail_ph:     "House no., moo, building, soi, road",
    address_set_default_toggle:"Set as default address",
    address_save:          "Save address",
    address_add:           "Add address",
    address_required:      "Please fill in required fields",
    address_set_default_toast:"Set as default address",
    address_deleted:       "Address deleted",
    address_edited:        "Address updated",
    address_added:         "Address added",

    cf_reason_title:       "Issue type",
    cf_return_addr_title:  "Address for replacement / return",
    cf_shipping_addr:      "Shipping address",
    cf_default:            "Default",
    cf_evidence:           "Photo evidence",
    cf_evidence_sub:       "Upload photos of the product, packaging or related evidence (JPEG, PNG, WebP, up to 5MB/file)",
    cf_upload_click:       "Click to upload photos",
    cf_upload_drag:        "Or drag files here",
    cf_upload_choose:      "Choose file",
    cf_more_detail:        "Additional details",
    cf_more_detail_ph:     "Describe the issue in detail...",
    cf_refund_items:       "Items to refund",
    cf_refund_details:     "Refund details",
    cf_refund_amount:      "Refund amount",
    cf_refund_channel:     "Refund channel",
    cf_refund_bank:        "TMB Thanachart Bank [*1234]",
    cf_email:              "Email",
    cf_actual_refund:      "Actual refund amount",
    cf_confirm:            "Confirm",
    cf_detail_required:    "Please describe the issue",
    cf_image_uploaded:     "Photo uploaded",
    cf_submitted:          "Complaint submitted",
    cs_complaint_info:     "Complaint info",
    cs_order_no:           "Order ID",
    cs_product:            "Product",
    cs_refund_amt:         "Refund amount",
    cs_refund_channel:     "Refund channel",
    cs_date:               "Submitted on",
    cs_type:               "Type",
    cs_email:              "Email",
    cs_details:            "Details",
    cs_shop_msg:           "Message from shop",
    cs_progress:           "Progress",
    cs_pending:            "Pending",
    cs_help:               "Need help?",
    cs_help_sub:           "For any questions, contact us at:",
    cs_help_hours:         "Mon - Fri 08:30 - 17:30",
    cs_step1_title:        "Complaint submitted",
    cs_step1_desc:         "We received your complaint",
    cs_step2_title:        "Reviewing",
    cs_step2_desc:         "Our team is reviewing the evidence",
    cs_step3_title:        "Approved & processing",
    cs_step3_desc:         "Replacement is being shipped",
    cs_step4_title:        "Replacement shipped",
    cs_step4_desc:         "Sending replacement to customer",
    cs_step5_title:        "Closed",
    cs_step5_desc:         "Complaint closed",
    cs_shop_msg_text:      "Sorry for the inconvenience. We have refunded xx.xx baht to your x123 Visa account.",
    cs_sample_detail:      "The box was heavily damaged. The product inside was broken and spilled, and cannot be used.",

    shop_chat:             "Chat with shop",
    shop_follow:           "Follow",
    shop_followed:         "Following",
    shop_products:         "Products",
    shop_followers:        "Followers",
    shop_response_rate:    "Response rate",
    shop_response_time:    "Response time",
    shop_rating:           "Rating",
    shop_joined:           "Joined",
    shop_tab_home:         "Home",
    shop_tab_products:     "Products",
    shop_tab_categories:   "Categories",
    shop_tab_about:        "About",
    shop_new_arrivals:     "New arrivals",
    shop_bestsellers:      "Best sellers",
    shop_all_products:     "All products",

    settings_title:        "Settings",
    settings_general:      "General",
    settings_language:     "Language",
    settings_notifications:"Notifications",
    settings_privacy:      "Privacy",
    settings_security:     "Security",
    settings_help:         "Help",
    settings_logout:       "Log out",
    settings_logout_confirm:"Are you sure you want to log out?",

    chat_typing:           "Typing...",
    chat_placeholder:      "Type a message...",
    chat_send:             "Send",
    chat_title:            "Chat with shops",
    chat_online:           "Online",
    chat_offline:          "Offline",
    chat_start_with:       "Start a chat with",
    chat_start_default:    "Start a chat...",
    chat_quick_q1:         "Product inquiry",
    chat_quick_q2:         "Order status",
    chat_quick_q3:         "Request receipt",
    chat_quick_q4:         "Report issue",
    notif_title:           "Notifications",
    notif_empty:           "No notifications",
    notif_mark_all:        "Mark all as read",
  },

  zh: {
    /* ===== appbar / common ===== */
    menu_home:          "首页",
    menu_products:      "产品",
    menu_market:        "草药市场",
    menu_blog:          "文章",
    menu_about:         "关于我们",
    button_login:       "登录",
    search_placeholder: "搜索产品、药草、品牌...",
    search_button:      "搜索",
    search_aria:        "搜索",
    close_aria:         "关闭",

    common_back:           "返回",
    common_cancel:         "取消",
    common_save:           "保存",
    common_confirm:        "确认",
    common_edit:           "编辑",
    common_delete:         "删除",
    common_change:         "更改",
    common_loading:        "加载中...",
    common_or:             "或",
    common_view_all:       "查看全部",
    common_view_details:   "查看详情",
    common_read_more:      "阅读更多",
    common_required:       "请填写完整信息",
    common_yes:            "是",
    common_no:             "否",
    common_close:          "关闭",
    common_submit:         "提交",
    common_send:           "发送",
    common_continue:       "继续",
    common_shop_now:       "立即购买",
    common_continue_shop:  "继续购物",
    common_apply:          "应用",
    common_items:          "件",
    common_pieces:         "件",
    common_pcs:            "件",
    common_qty:            "数量",
    common_total:          "合计",
    common_subtotal:       "小计",
    common_discount:       "折扣",
    common_shipping:       "运费",
    common_free:           "免费",
    common_sort:           "排序",
    common_sort_desc:      "价格:从高到低",
    common_sort_asc:       "价格:从低到高",
    common_filter:         "筛选",
    common_reset_filter:   "清除筛选",
    common_prev_page:      "上一页",
    common_next_page:      "下一页",
    common_no_orders:      "暂无订单",
    common_not_found:      "未找到",
    common_optional:       "选填",
    common_required_mark:  "*",
    common_search_results: "搜索结果",
    common_results_found:  "找到",

    login_welcome:         "欢迎登录",
    login_subtitle:        "用精选草本产品守护您的健康",
    login_subtitle2:       "立即在 Metaherb 在线购物",
    login_email_label:     "邮箱或用户名",
    login_email_ph:        "请输入邮箱或用户名",
    login_password_label:  "密码",
    login_password_ph:     "请输入密码",
    login_forgot:          "忘记密码?",
    login_demo:            "测试账户(点击自动填充):",
    login_button:          "登录",
    login_no_account:      "还没有账户?",
    login_register_link:   "注册",
    login_invalid:         "邮箱或密码错误",
    register_title:        "注册账户",
    register_role_label:   "账户类型",
    register_role_user:    "买家",
    register_role_owner:   "卖家",
    register_username_label:"用户名",
    register_username_ph:  "请输入用户名",
    register_password_label:"密码",
    register_password_ph:  "至少8位字符",
    register_email_label:  "邮箱",
    register_email_ph:     "请输入邮箱",
    register_phone_label:  "手机号",
    register_phone_ph:     "请输入手机号",
    register_accept:       "我接受",
    register_terms:        "Meta Herb 服务条款",
    register_and:          "和",
    register_privacy:      "隐私政策",
    register_button:       "注册",
    register_has_account:  "已有账户?",
    register_login_link:   "登录",
    register_password_min: "密码至少需要8位字符",
    register_accept_terms: "请接受条款",

    home_recommended:      "推荐商品",
    home_flash_sale:       "限时秒杀",
    home_articles:         "精选文章",
    home_videos:           "精选视频",
    home_recommended_tag:  "推荐",
    home_discount_prefix:  "-",
    cat_herb:              "草药",
    cat_food:              "食品",
    cat_medicine:          "药品",
    cat_aroma:             "香薰",
    cat_beauty:            "美容",
    cat_giftset:           "礼盒",
    cat_tea:               "草本茶",
    cat_supplement:        "保健品",
    cat_oil:               "精油",

    products_title:        "全部商品",
    products_filter:       "筛选",
    products_category:     "类别",
    products_type:         "商品类型",
    products_price_range:  "价格区间",
    products_all:          "全部",
    products_type_flash:   "限时秒杀",
    products_type_promo:   "促销商品",
    products_type_rec:     "推荐商品",
    products_showing:      "显示",
    products_of:           "/",
    products_results:      "件",

    pd_back_to_products:   "返回商品列表",
    pd_in_stock:           "有货",
    pd_out_of_stock:       "缺货",
    pd_quantity:           "数量",
    pd_available:          "件可售",
    pd_options:            "规格",
    pd_select_option:      "选择规格",
    pd_add_to_cart:        "加入购物车",
    pd_buy_now:            "立即购买",
    pd_chat:               "与卖家聊天",
    pd_description:        "商品描述",
    pd_specs:              "规格参数",
    pd_reviews:            "商品评价",
    pd_related:            "相关商品",
    pd_sold:               "已售",
    pd_rating:             "评分",
    pd_shop:               "店铺",
    pd_visit_shop:         "进入店铺",
    pd_added_to_cart:      "已加入购物车",
    pd_added_to_wishlist:  "已加入收藏",
    pd_removed_from_wishlist:"已取消收藏",
    pd_select_option_first:"请先选择规格",
    pd_share:              "分享",
    pd_copy_link:          "链接已复制!",
    pd_all_reviews:        "全部评价",
    pd_write_review:       "写评价",
    pd_filter_reviews:     "筛选评价",
    pd_with_image:         "带图评价",
    pd_specifications:     "规格参数",
    pd_no_reviews:         "暂无评价",
    pd_price:              "价格",
    pd_options_label:      "规格",
    pd_quantity_label:     "数量",
    pd_remaining:          "仅剩",
    pd_add_to_cart_btn:    "加入购物车",
    pd_added_btn:          "已加入!",
    pd_buy_now_btn:        "立即购买",
    pd_product_details:    "商品详情",
    pd_product_specs:      "规格参数",
    pd_weight:             "净重:",
    pd_type:               "类型:",
    pd_sku:                "商品编号:",
    pd_format:             "形态:",
    pd_shop_items:         "商品",
    pd_shop_items_unit:    "件",
    pd_shop_rating:        "店铺评分",
    pd_all_ratings:        "全部评分 100",
    pd_loved_items:        "喜欢",
    pd_view_shop:          "查看店铺",
    pd_ask_shop:           "咨询店铺",
    pd_review_option_prefix:"规格:",
    pd_recommended_for_you:"为您推荐",
    pd_all_filter:         "全部",
    pd_view_review_image:  "查看评价图片",
    pd_prev:               "上一页",
    pd_next:               "下一页",

    cart_title:            "购物车",
    cart_empty:            "购物车是空的",
    cart_empty_sub:        "把您喜欢的商品加入购物车",
    cart_select_all:       "全选",
    cart_delete_selected:  "删除选中",
    cart_shop_recommend:   "推荐店铺",
    cart_chat_shop:        "与店铺聊天",
    cart_out_of_stock:     "缺货",
    cart_shop_voucher:     "店铺优惠券:满 ฿300 减 ฿30",
    cart_code:             "优惠码",
    cart_summary:          "订单摘要",
    cart_selected_items:   "已选商品",
    cart_subtotal:         "商品小计",
    cart_discount:         "折扣",
    cart_shipping:         "运费",
    cart_grand_total:      "总计",
    cart_protected:        "您的购物受到保护",
    cart_checkout:         "去结算",
    cart_continue:         "继续购物",
    cart_removed:          "已从购物车移除",
    cart_removed_selected: "已删除选中商品",
    cart_coupon_applied:   "优惠券使用成功!",
    cart_coupon_removed:   "已移除优惠券",
    cart_discount_amount:  "已优惠 ฿100.00",

    pay_title:             "结算",
    pay_empty:             "购物车是空的",
    pay_shop_now:          "立即购买",
    pay_address_title:     "收货地址",
    pay_change:            "更改",
    pay_default_address:   "默认",
    pay_add_new_address:   "+ 新增地址",
    pay_shipping_title:    "配送选项",
    pay_shipping_eta:      "2月18日 - 2月20日送达",
    pay_method_title:      "支付方式",
    pay_method_promptpay:  "PromptPay",
    pay_method_promptpay_desc:"扫描二维码支付",
    pay_method_bank:       "银行转账",
    pay_method_bank_desc:  "转账到店铺银行账户",
    pay_method_credit:     "信用卡 / 借记卡",
    pay_method_credit_desc:"使用信用卡或借记卡支付",
    pay_method_cod:        "货到付款",
    pay_method_cod_desc:   "收到商品后付款",
    pay_summary:           "订单摘要",
    pay_option:            "规格 1",
    pay_qty_text:          "数量",
    pay_coupon:            "优惠券",
    pay_subtotal:          "商品小计",
    pay_discount:          "折扣",
    pay_vat:               "增值税 7%",
    pay_shipping:          "运费",
    pay_grand_total:       "应付总额",
    pay_confirm:           "提交订单",

    vp_title:              "等待付款",
    vp_subtitle:           "请在24小时内付款,以免订单被取消",
    vp_amount:             "应付金额",
    vp_promptpay:          "使用 PromptPay 付款",
    vp_remaining:          "剩余付款时间 24:00:00",
    vp_receiver:           "收款人:",
    vp_receiver_name:      "测试系统",
    vp_promptpay_no:       "PromptPay号码:",
    vp_warning:            "重要:请勿与他人分享此二维码,付款前请核对金额",
    vp_view_order:         "查看订单详情",
    vp_all_orders:         "全部订单",
    vp_continue_shop:      "继续购物",
    vp_method:             "支付方式:",
    vp_amount_label:       "金额:",
    vp_status:             "付款状态:",
    vp_pending:            "等待付款",
    vp_upload_title:       "上传付款凭证",
    vp_upload_sub:         "请上传转账凭证以便我们核实并发货",
    vp_upload_choose:      "选择图片文件 (JPG, PNG)",
    vp_not_found:          "未找到订单",

    orders_title:          "我的订单",
    orders_tab_all:        "全部",
    orders_tab_pending:    "待付款",
    orders_tab_preparing:  "备货中",
    orders_tab_shipped:    "已发货",
    orders_tab_delivered:  "已送达",
    orders_tab_completed:  "已完成",
    orders_tab_cancelled:  "已取消",
    orders_status_pending_payment: "待付款",
    orders_status_pending_verify:  "审核中",
    orders_status_preparing:       "备货中",
    orders_status_shipped:         "已发货",
    orders_status_delivered:       "已收货",
    orders_status_completed:       "已完成",
    orders_status_cancelled:       "已取消",
    orders_empty:          "暂无订单",
    orders_shop_now:       "去购物",
    orders_view_details:   "查看详情",
    orders_view_all_items: "查看全部",
    orders_status_label:   "订单状态",
    orders_tracking_no:    "运单号:",
    orders_tracking_copied:"运单号已复制",
    orders_total_label:    "订单总额:",
    orders_btn_cancel:     "取消",
    orders_btn_pay:        "去付款",
    orders_btn_edit:       "修改信息",
    orders_btn_contact:    "联系卖家",
    orders_btn_confirm_received:"确认收货",
    orders_btn_complaint:  "申请售后",
    orders_btn_review:     "评价",
    orders_btn_buy_again:  "再次购买",
    orders_btn_rebuy:      "重新购买",
    orders_cancelled_toast:"订单已取消",
    orders_received_toast: "已确认收货!",
    orders_id_copied:      "订单号已复制",
    review_title:          "评价商品",
    review_tap_star:       "点击星星评分",
    review_rating_1:       "很差",
    review_rating_2:       "不好",
    review_rating_3:       "一般",
    review_rating_4:       "好",
    review_rating_5:       "非常好",
    review_tag_good:       "商品好",
    review_tag_fast:       "发货快",
    review_tag_package:    "包装好",
    review_tag_worth:      "性价比高",
    review_tag_accurate:   "与描述相符",
    review_placeholder:    "写下您的评价...",
    review_submit:         "提交评价",
    review_thanks:         "感谢您的评价!",
    refund_title:          "申请退款/退货",
    refund_subtitle:       "请选择退款原因",
    refund_reason_desc:    "商品与描述不符",
    refund_reason_damaged: "商品损坏",
    refund_reason_wrong:   "收到错误商品",
    refund_reason_qty:     "数量不对",
    refund_reason_change:  "改变主意",
    refund_reason_other:   "其他",
    refund_detail_ph:      "其他详情 (选填)",
    refund_submit:         "提交申请",
    refund_success:        "退款申请已提交",
    refund_success_desc:   "我们将在1-3个工作日内审核",
    complaint_select_title:"请说明问题",
    complaint_order_label: "订单:",
    complaint_type_damaged:"商品损坏",
    complaint_type_damaged_desc:"运输中破损、变形或损坏的商品",
    complaint_type_wrong:  "商品不符",
    complaint_type_wrong_desc:"收到与订单不符的商品",
    complaint_type_return: "退货",
    complaint_type_return_desc:"退还商品换取额度或新品",
    complaint_type_refund: "退款",
    complaint_type_refund_desc:"申请订单退款",

    blog_title:            "全部文章",
    blog_articles:         "文章",
    blog_videos:           "视频",
    blog_read_more:        "阅读更多",
    blog_share:            "分享文章",
    blog_views:            "浏览量",
    blog_copy_link:        "链接已复制!",

    coupon_title:          "METAHERB 优惠券",
    coupon_tab_all:        "全部",
    coupon_tab_discount:   "折扣券",
    coupon_tab_freeship:   "免运券",
    coupon_min:            "最低消费",
    coupon_terms:          "使用条款",
    coupon_collected:      "已领取",
    coupon_collect:        "领取",
    coupon_received:       "已成功领取优惠券!",
    coupon_discount_label: "折扣码",
    coupon_free_label:     "免运码",
    coupon_express:        "快递",
    coupon_all_shops:      "所有店铺",
    my_coupons_title:      "我的优惠券",
    my_coupons_collect_more:"领取更多优惠券",
    my_coupons_tab_used:   "已使用",
    my_coupons_tab_expired:"已过期",
    my_coupons_use:        "使用",
    my_coupons_expired:    "已过期",
    my_coupons_use_toast:  "已选择优惠券!",
    my_coupons_empty:      "该分类下暂无优惠券",
    my_coupons_empty_sub:  "去领取更多优惠券吧!",
    my_coupons_go:         "领取优惠券",

    wishlist_title:        "心愿单",
    wishlist_empty:        "还没有喜欢的商品",
    wishlist_shop:         "去购物",
    wishlist_add_cart:     "加入购物车",
    wishlist_added_cart:   "已加入购物车",
    wishlist_count_unit:   "件",

    about_welcome:         "欢迎",
    about_hero_1:          "从植物",
    about_hero_2:          "到产品",
    about_hero_3:          "MetaHerb",
    about_subtitle:        "即使是稀有草药,MetaHerb",
    about_subtitle2:       "也能为您精心甄选与采购",
    about_cta_shop:        "立即购买",
    about_cta_mission:     "我们的使命",
    about_scroll:          "向下滚动查看更多",
    about_our_story:       "我们的故事",
    about_story_h1:        "从农民田间",
    about_story_h2:        "到泰国千家万户",
    about_story_sub:       "MetaHerb——优质草本健康的引领者",
    about_feat1_title:     "纯天然来源",
    about_feat1_desc:      "所有草本均由清莱府美斯乐山120多莱有机种植区的当地农民精心栽培,严格遵循有机标准。",
    about_feat2_title:     "传统智慧融合现代创新",
    about_feat2_desc:      "我们将传承200多年的泰国传统草药智慧与现代生产技术相结合,确保产品高效又安全。",
    about_feat3_title:     "国际标准认证",
    about_feat3_desc:      "每件产品在送达顾客之前,均通过泰国FDA、Organic Thailand 和 ISO 22000 认证。",
    about_trust_h1:        "建立信任",
    about_trust_h2:        "源于标准",
    about_product_featured:"我们的精选产品",
    about_tag_bestseller:  "畅销第一",
    about_tag_new:         "新品",
    about_tag_popular:     "热卖",
    about_mission_h1:      "使命与愿景",
    about_mission_h2:      "我们为何而工作?",
    about_mission_quote:   '"引领泰国草本走向世界市场"',
    about_mission_desc:    "致力于将优质泰国草本带给消费者,守护可持续的健康。",
    about_stat_years:      "年经验",
    about_stat_farm:       "莱有机农场",
    about_stat_products:   "草本产品",
    about_stat_customers:  "泰国客户",
    about_contact_h1:      "与我们交谈",
    about_contact_h2:      "全渠道联系",
    about_contact_sub:     "我们随时为您提供草本和产品咨询,请通过您方便的渠道联系我们。",
    about_contact_info:    "联系方式",
    about_phone:           "电话",
    about_phone_hours:     "周一至周五:08:30 - 17:30",
    about_email:           "邮箱",
    about_email_reply:     "24小时内回复",
    about_address:         "地址",
    about_follow_us:       "在社交媒体上关注我们",
    about_send_message:    "给我们留言",
    about_form_sub:        "请填写以下表单",
    about_form_name:       "姓名",
    about_form_name_ph:    "您的姓名",
    about_form_email:      "邮箱",
    about_form_email_ph:   "您的邮箱",
    about_form_subject:    "主题",
    about_form_subject_ph: "联系主题",
    about_form_message:    "留言",
    about_form_message_ph: "请输入您的留言...",
    about_form_send:       "发送留言",
    about_form_success:    "留言发送成功!",
    about_form_success_desc:"我们将在24小时内回复您",

    account_title:         "我的账户",
    account_role:          "角色",
    account_role_user:     "用户",
    account_role_owner:    "店主",
    account_role_admin:    "管理员",
    account_change_avatar: "更换头像",
    account_avatar_sub:    "支持格式:JPEG, PNG, GIF, WebP",
    account_avatar_size:   "大小限制:5MB",
    account_user_info:     "用户信息",
    account_edit:          "编辑",
    account_username:      "用户名",
    account_email:         "邮箱",
    account_phone:         "手机号",
    account_password:      "您的密码",
    account_change_pw:     "修改密码",
    account_password_label:"密码",
    account_current_pw:    "当前密码",
    account_new_pw:        "新密码",
    account_confirm_pw:    "确认新密码",
    account_current_pw_ph: "输入当前密码",
    account_new_pw_ph:     "输入新密码",
    account_confirm_pw_ph: "再次输入新密码",
    account_pw_mismatch:   "两次输入的密码不一致",
    account_settings:      "设置",
    account_about_notif:   "通知设置",
    account_notif_orders:  "订单通知",
    account_notif_promo:   "促销通知",
    account_notif_msg:     "消息通知",
    account_notif_status:  "商品状态通知",
    account_saved:         "信息已保存",
    account_pw_changed:    "密码已修改",

    address_title:         "收货地址",
    address_add_new:       "新增地址",
    address_default:       "默认",
    address_set_default:   "设为默认",
    address_edit_title:    "编辑地址",
    address_add_title:     "新增地址",
    address_first_name:    "名字",
    address_last_name:     "姓氏",
    address_first_name_ph: "收件人名字",
    address_last_name_ph:  "姓氏",
    address_phone:         "手机号",
    address_phone_ph:      "请输入手机号",
    address_addr_label:    "地址",
    address_addr_ph:       "邮编、区/街道",
    address_detail:        "详细地址",
    address_detail_ph:     "门牌号、村、楼栋、巷、路",
    address_set_default_toggle:"设为默认地址",
    address_save:          "保存地址",
    address_add:           "添加地址",
    address_required:      "请填写必填项",
    address_set_default_toast:"已设为默认地址",
    address_deleted:       "地址已删除",
    address_edited:        "地址已修改",
    address_added:         "地址已添加",

    cf_reason_title:       "投诉原因",
    cf_return_addr_title:  "换货/退货地址",
    cf_shipping_addr:      "收货地址",
    cf_default:            "默认",
    cf_evidence:           "图片凭证",
    cf_evidence_sub:       "上传商品、包装或相关凭证图片(JPEG、PNG、WebP,单个文件不超过5MB)",
    cf_upload_click:       "点击上传图片",
    cf_upload_drag:        "或将文件拖到此处",
    cf_upload_choose:      "选择文件",
    cf_more_detail:        "其他详情",
    cf_more_detail_ph:     "请详细描述问题...",
    cf_refund_items:       "退款商品",
    cf_refund_details:     "退款详情",
    cf_refund_amount:      "退款金额",
    cf_refund_channel:     "退款渠道",
    cf_refund_bank:        "TMB Thanachart 银行 [*1234]",
    cf_email:              "邮箱",
    cf_actual_refund:      "实际退款金额",
    cf_confirm:            "确认",
    cf_detail_required:    "请填写问题详情",
    cf_image_uploaded:     "图片上传成功",
    cf_submitted:          "投诉已提交",
    cs_complaint_info:     "投诉信息",
    cs_order_no:           "订单编号",
    cs_product:            "商品",
    cs_refund_amt:         "退款金额",
    cs_refund_channel:     "退款渠道",
    cs_date:               "提交日期",
    cs_type:               "类型",
    cs_email:              "邮箱",
    cs_details:            "详情",
    cs_shop_msg:           "店铺留言",
    cs_progress:           "处理进度",
    cs_pending:            "待处理",
    cs_help:               "需要帮助?",
    cs_help_sub:           "如有疑问,请联系我们:",
    cs_help_hours:         "周一至周五 08:30 - 17:30",
    cs_step1_title:        "投诉已提交",
    cs_step1_desc:         "我们已收到您的投诉",
    cs_step2_title:        "信息审核中",
    cs_step2_desc:         "团队正在审核证据和信息",
    cs_step3_title:        "已批准并处理",
    cs_step3_desc:         "替换商品正在配送中",
    cs_step4_title:        "替换商品发货",
    cs_step4_desc:         "正在为客户配送替换商品",
    cs_step5_title:        "完成",
    cs_step5_desc:         "投诉已关闭",
    cs_shop_msg_text:      "对于带来的不便深感抱歉,本店已将 xx.xx 泰铢退至您的 x123 Visa 账户。",
    cs_sample_detail:      "包装盒严重破损,内部产品破裂泄漏,无法使用。",

    shop_chat:             "联系店铺",
    shop_follow:           "关注",
    shop_followed:         "已关注",
    shop_products:         "商品",
    shop_followers:        "粉丝",
    shop_response_rate:    "回复率",
    shop_response_time:    "回复时间",
    shop_rating:           "评分",
    shop_joined:           "加入时间",
    shop_tab_home:         "店铺首页",
    shop_tab_products:     "全部商品",
    shop_tab_categories:   "分类",
    shop_tab_about:        "关于店铺",
    shop_new_arrivals:     "新品上架",
    shop_bestsellers:      "热销商品",
    shop_all_products:     "全部商品",

    settings_title:        "设置",
    settings_general:      "通用",
    settings_language:     "语言",
    settings_notifications:"通知",
    settings_privacy:      "隐私",
    settings_security:     "安全",
    settings_help:         "帮助",
    settings_logout:       "退出登录",
    settings_logout_confirm:"确定要退出登录吗?",

    chat_typing:           "正在输入...",
    chat_placeholder:      "输入消息...",
    chat_send:             "发送",
    chat_title:            "联系店铺",
    chat_online:           "在线",
    chat_offline:          "离线",
    chat_start_with:       "开始与",
    chat_start_default:    "开始聊天...",
    chat_quick_q1:         "商品咨询",
    chat_quick_q2:         "订单状态",
    chat_quick_q3:         "索取发票",
    chat_quick_q4:         "报告问题",
    notif_title:           "通知",
    notif_empty:           "暂无通知",
    notif_mark_all:        "全部标为已读",
  },
} as const;

export type TKey = keyof typeof translations.th;

const STORAGE_KEY = "metaherb-lang";

interface LanguageContextValue {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: TKey) => string;
}

const LanguageContext = createContext<LanguageContextValue>({
  lang: "th",
  setLang: () => {},
  t: (k) => translations.th[k],
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    if (typeof window === "undefined") return "th";
    const stored = window.localStorage.getItem(STORAGE_KEY) as Lang | null;
    if (stored && (stored === "th" || stored === "en" || stored === "zh")) return stored;
    return "th";
  });

  useEffect(() => {
    try { window.localStorage.setItem(STORAGE_KEY, lang); } catch {}
    document.documentElement.lang = lang;
  }, [lang]);

  const setLang = (l: Lang) => setLangState(l);
  const t = (key: TKey) => translations[lang][key] ?? translations.th[key];

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
